### ISSUE TITLE
Thank you !

### ISSUE THREAD

**Issue by TintinJS** [ratte/mixxxcontrollermapping#1]
# Thank you !

So Hercules DJ Control Instinct work properly on Linux with Mixx ?

**Comment by TintinJS** [comment]
yes it does !

**Comment by TintinJS** [comment]
But, i don't know how to add lights :/

**Comment by ratte** [comment]
as you can see in the Readme (pt 6), it is not yet implemented...
Will look, if i can find time the next 2 weeks.
